### ISSUE TITLE
Failed to launch JVM

### ISSUE THREAD

**Issue by Jeevasimba** [nokeedev/gradle-native#605]
I am using github action to create jni lib for windows. After creating jni lib from github action I download and check that lib in my computer it worked smoothly.

![qt action](https://user-images.githubusercontent.com/96039278/166094337-48db38be-6481-42f0-9407-201489de1fa5.PNG)

I am using only c++ language in jni side the lib worked on my computer.

But , If I am using c++ with qt framework in jni side. I tested run test in github action the lib gives output in github action. But If I run on my  computer it comes an error like this 

![failed to launch jvm](https://user-images.githubusercontent.com/96039278/166109065-18a0f3ef-02c8-46a0-a708-6dc1b21f6375.PNG)

> **ERROR**
> 
> ```
>  Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\prade\Documents\jeeva-main\psfe\build\lib\main\psfe.dll: Can't find dependent libraries
> at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
> at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
> at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
> at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
> at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
> at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)
> at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2422)
> at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
> at java.base/java.lang.System.loadLibrary(System.java:1989)
> at Pj.nativecodes.<clinit>(nativecodes.java:6)
> at Pj.Launcher.main(Launcher.java:7)
> ```
> 
> I searched a solution for this error [Answer](https://stackoverflow.com/a/6092576/17777351).
> 
> How can I solve this error ?

If I remove qt framework code from my c++ file the jni lib works smoothly on my computer.

![jni qt](https://user-images.githubusercontent.com/96039278/166094262-ee07dca3-4a05-4fbe-bd2a-1147a3f66563.PNG)

How can I solve this issue ?

**Comment by lacasseio** [comment]
What most likely is missing is the runtime shared library for QT? There are several ways to solve this depending on how you end up running your application or executing code inside your library.

**Comment by lacasseio** [comment]
If you have a sample, we can look into it to make it work.

**Comment by Jeevasimba** [comment]
**1. Configure library target machines**

    library {
        targetMachines = [
            machines.linux.x86_64,
            machines.windows.x86, machines.windows.x86_64,
            machines.macOS.x86_64
        ]
    }


**2. Configure library linkages**

    library {
        linkage = [Linkage.STATIC, Linkage.SHARED]
    }


I can't understant the above first and 2 code. I want to create JNI lib with specific architecture.

Can you explain what is the purpose of those code ? please !!!

**Comment by Jeevasimba** [comment]
I am using gradle to build c++ library 

[C++ library gradle reference][1]

**1. Configure library target machines**

    library {
        targetMachines = [
            machines.linux.x86_64,
            machines.windows.x86, machines.windows.x86_64,
            machines.macOS.x86_64
        ]
    }


**2. Configure library linkages**

    library {
        linkage = [Linkage.STATIC, Linkage.SHARED]
    }


I can't understant the above targetmachines and linkage code. I want to create c++ library with specific architecture.

Can any one explain what is the purpose of those code ? 


  [1]: https://docs.gradle.org/current/userguide/cpp_library_plugin.html
